- name: install required packages
  apt:
    name:
    - python3-setuptools
    - python3-pip
    - unzip
    state: present

- name: install python packages
  pip:
    state: present
    name: "{{ item }}"
    executable: "/usr/bin/pip3"
  loop:
    - boto
    - boto3
    - botocore